services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale-obsidian
    hostname: obsidian-docker
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=true # Useful for MagicDNS
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:41234
    volumes:
      - ./tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:41234/healthz"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    network_mode: service:tailscale
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./obsidian/config:/config
    shm_size: "1gb"
    depends_on:
      tailscale:
        condition: service_healthy
    restart: unless-stopped
